import PDFDocument from "pdfkit";
import { Artifact } from "./instagram-collector";
import { BrandDna } from "./brand-analyzer";
import { CompetitorInsight } from "./competitor-analyzer";
import { GeneratedPost } from "./post-generator";

export interface ReportData {
  targetHandle: string;
  brandDna: BrandDna;
  competitorInsights: CompetitorInsight[];
  generatedPosts: GeneratedPost[];
  artifacts: Artifact[];
  timestamp: string;
}

export class PDFRenderer {
  generateReport(data: ReportData): PDFDocument {
    const doc = new PDFDocument({ margin: 50, size: "A4" });

    // Title page
    this.addTitle(doc, "Smart Prompt Lab Analysis Report");
    this.addSubtitle(doc, `Instagram Account: @${data.targetHandle}`);
    this.addText(doc, `Generated: ${new Date(data.timestamp).toLocaleString()}`);
    doc.moveDown(2);

    // Executive Summary
    this.addSectionHeader(doc, "Executive Summary");
    this.addText(doc, `This report analyzes @${data.targetHandle} and ${data.competitorInsights.length} competitor accounts.`);
    this.addText(doc, `A total of ${data.artifacts.length} artifacts were collected and analyzed.`);
    this.addText(doc, `${data.generatedPosts.length} post recommendations have been generated.`);
    doc.moveDown(1);

    // Brand DNA Section
    this.addSectionHeader(doc, "Brand DNA Analysis");
    
    this.addSubheader(doc, "Observed Characteristics");
    data.brandDna.observed.forEach(obs => {
      this.addBullet(doc, obs);
    });
    doc.moveDown(0.5);

    this.addSubheader(doc, "Inferred Insights");
    data.brandDna.inferred.forEach(inf => {
      this.addBullet(doc, inf);
    });
    doc.moveDown(1);

    // Competitor Analysis Section
    this.addSectionHeader(doc, "Competitor Analysis");
    data.competitorInsights.forEach((insight, idx) => {
      this.addSubheader(doc, `${idx + 1}. @${insight.handle}`);
      this.addText(doc, `Average Engagement: ${insight.engagementAvg} likes`);
      this.addText(doc, `Top Formats: ${insight.topFormats.join(", ")}`);
      this.addText(doc, `Common Themes: ${insight.commonThemes.join(", ")}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);

    // Generated Posts Section
    this.addSectionHeader(doc, "Generated Post Recommendations");
    data.generatedPosts.forEach((post, idx) => {
      this.addSubheader(doc, `Post ${idx + 1}: ${post.format}`);
      this.addText(doc, `Caption: ${post.caption}`);
      this.addText(doc, `Hashtags: ${post.hashtags.join(" ")}`);
      this.addText(doc, `Reasoning: ${post.reasoning}`, { italic: true });
      doc.moveDown(0.5);
    });

    // Footer
    doc.moveDown(2);
    this.addText(doc, "---", { align: "center" });
    this.addText(doc, "Generated by Smart Prompt Lab", { align: "center", fontSize: 10 });
    this.addText(doc, "https://github.com/Xophur/smart-prompt-lab-core", { align: "center", fontSize: 8 });

    return doc;
  }

  private addTitle(doc: PDFDocument, text: string): void {
    doc.fontSize(24)
       .fillColor("#2C3E50")
       .text(text, { align: "center" })
       .moveDown(0.5);
  }

  private addSubtitle(doc: PDFDocument, text: string): void {
    doc.fontSize(16)
       .fillColor("#34495E")
       .text(text, { align: "center" })
       .moveDown(0.3);
  }

  private addSectionHeader(doc: PDFDocument, text: string): void {
    doc.fontSize(18)
       .fillColor("#2C3E50")
       .text(text)
       .moveDown(0.5);
  }

  private addSubheader(doc: PDFDocument, text: string): void {
    doc.fontSize(14)
       .fillColor("#34495E")
       .text(text)
       .moveDown(0.3);
  }

  private addText(
    doc: PDFDocument,
    text: string,
    options?: { align?: "left" | "center" | "right"; fontSize?: number; italic?: boolean }
  ): void {
    const fontSize = options?.fontSize || 11;
    const align = options?.align || "left";
    const font = options?.italic ? "Helvetica-Oblique" : "Helvetica";

    doc.fontSize(fontSize)
       .fillColor("#000000")
       .font(font)
       .text(text, { align })
       .font("Helvetica")
       .moveDown(0.3);
  }

  private addBullet(doc: PDFDocument, text: string): void {
    doc.fontSize(11)
       .fillColor("#000000")
       .text(`• ${text}`, { indent: 20 })
       .moveDown(0.2);
  }
}
